# Generated by Django 5.0.1 on 2025-12-30 04:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.CharField(choices=[('1-1', '1학년 1학기'), ('1-2', '1학년 2학기'), ('2-1', '2학년 1학기'), ('2-2', '2학년 2학기'), ('3-1', '3학년 1학기'), ('3-2', '3학년 2학기')], max_length=10, verbose_name='학기')),
                ('exam_type', models.CharField(choices=[('MIDTERM', '중간고사'), ('FINAL', '기말고사'), ('MOCK', '모의고사'), ('OVERALL', '전체')], max_length=20, verbose_name='시험 유형')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text='전 과목 평균 등급', max_digits=4, null=True, verbose_name='평균 등급')),
                ('korean_score', models.IntegerField(blank=True, null=True, verbose_name='국어 점수')),
                ('korean_grade', models.IntegerField(blank=True, null=True, verbose_name='국어 등급')),
                ('math_score', models.IntegerField(blank=True, null=True, verbose_name='수학 점수')),
                ('math_grade', models.IntegerField(blank=True, null=True, verbose_name='수학 등급')),
                ('english_score', models.IntegerField(blank=True, null=True, verbose_name='영어 점수')),
                ('english_grade', models.IntegerField(blank=True, null=True, verbose_name='영어 등급')),
                ('science1_score', models.IntegerField(blank=True, null=True, verbose_name='과학1 점수')),
                ('science1_grade', models.IntegerField(blank=True, null=True, verbose_name='과학1 등급')),
                ('science2_score', models.IntegerField(blank=True, null=True, verbose_name='과학2 점수')),
                ('science2_grade', models.IntegerField(blank=True, null=True, verbose_name='과학2 등급')),
                ('history_score', models.IntegerField(blank=True, null=True, verbose_name='한국사 점수')),
                ('history_grade', models.IntegerField(blank=True, null=True, verbose_name='한국사 등급')),
                ('total_score', models.IntegerField(blank=True, null=True, verbose_name='총점')),
                ('percentile', models.DecimalField(blank=True, decimal_places=2, help_text='상위 몇 %', max_digits=5, null=True, verbose_name='백분위')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '성적',
                'verbose_name_plural': '성적',
                'db_table': 'grades',
                'ordering': ['semester', 'exam_type'],
                'unique_together': {('student', 'semester', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50, verbose_name='과목명')),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='원점수')),
                ('standard_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='표준점수')),
                ('grade_rank', models.DecimalField(blank=True, decimal_places=2, help_text='1~9등급', max_digits=3, null=True, verbose_name='등급')),
                ('percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='백분위')),
                ('class_rank', models.IntegerField(blank=True, null=True, verbose_name='반 석차')),
                ('class_total', models.IntegerField(blank=True, null=True, verbose_name='반 인원')),
                ('grade_rank_in_school', models.IntegerField(blank=True, null=True, verbose_name='학년 석차')),
                ('grade_total_in_school', models.IntegerField(blank=True, null=True, verbose_name='학년 인원')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='grades.grade', verbose_name='성적')),
            ],
            options={
                'verbose_name': '과목별 성적',
                'verbose_name_plural': '과목별 성적',
                'db_table': 'subject_grades',
                'ordering': ['subject_name'],
                'unique_together': {('grade', 'subject_name')},
            },
        ),
    ]
