# Generated by Django 4.2.9 on 2025-12-31 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0001_initial"),
        ("grades", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "성적",
                "verbose_name_plural": "성적",
            },
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="grade",
            name="corrected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrected_grades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="정정한 사용자",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="correction_reason",
            field=models.TextField(
                blank=True, help_text="성적 정정 시 사유 입력", verbose_name="정정 사유"
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="is_latest",
            field=models.BooleanField(default=True, verbose_name="최신 버전 여부"),
        ),
        migrations.AddField(
            model_name="grade",
            name="version",
            field=models.IntegerField(default=1, verbose_name="버전"),
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("student", "semester", "exam_type", "version")},
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student", "semester"], name="grades_student_d7db4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student", "exam_type"], name="grades_student_436a3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student", "is_latest"], name="grades_student_de1fe7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(fields=["is_latest"], name="grades_is_late_7ae456_idx"),
        ),
    ]
