# Generated by Django 5.0.1 on 2025-12-30 04:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='학교명')),
                ('region', models.CharField(db_index=True, max_length=50, verbose_name='지역')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='구/군')),
                ('school_type', models.CharField(choices=[('일반고', '일반고'), ('특목고', '특목고'), ('자사고', '자율형사립고'), ('특성화고', '특성화고')], default='일반고', max_length=20, verbose_name='학교 유형')),
                ('ranking', models.IntegerField(blank=True, null=True, verbose_name='전국 순위')),
                ('statistics', models.JSONField(blank=True, default=dict, verbose_name='진학 통계')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '고등학교',
                'verbose_name_plural': '고등학교',
                'db_table': 'high_schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='대학명')),
                ('university_type', models.CharField(choices=[('국립', '국립'), ('사립', '사립'), ('의대', '의과대학'), ('교대', '교육대학')], default='사립', max_length=20, verbose_name='대학 유형')),
                ('ranking', models.IntegerField(blank=True, null=True, verbose_name='순위')),
                ('region', models.CharField(max_length=50, verbose_name='지역')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='추가 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '대학교',
                'verbose_name_plural': '대학교',
                'db_table': 'universities',
                'ordering': ['ranking', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityAdmissionCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100, verbose_name='학과명')),
                ('admission_type', models.CharField(choices=[('수시', '수시'), ('정시', '정시'), ('특기자', '특기자'), ('학생부종합', '학생부종합'), ('학생부교과', '학생부교과')], max_length=20, verbose_name='전형 유형')),
                ('year', models.IntegerField(verbose_name='전형 연도')),
                ('criteria', models.JSONField(default=dict, verbose_name='전형 상세')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_criteria', to='schools.university', verbose_name='대학')),
            ],
            options={
                'verbose_name': '대학 입학 전형',
                'verbose_name_plural': '대학 입학 전형',
                'db_table': 'university_admission_criteria',
                'ordering': ['-year', 'university', 'department'],
                'unique_together': {('university', 'department', 'admission_type', 'year')},
            },
        ),
    ]
