# Generated by Django 5.0.1 on 2025-12-30 04:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('TRANSCRIPT', '생활기록부'), ('REPORT', '성적표'), ('RECOMMENDATION', '추천서'), ('ESSAY', '자기소개서'), ('PORTFOLIO', '포트폴리오'), ('CERTIFICATE', '수상/자격증'), ('OTHER', '기타')], max_length=50, verbose_name='서류 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='파일')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='파일 크기 (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME 타입')),
                ('status', models.CharField(choices=[('UPLOADED', '업로드됨'), ('PROCESSING', '처리중'), ('COMPLETED', '완료'), ('FAILED', '실패')], default='UPLOADED', max_length=20, verbose_name='처리 상태')),
                ('ocr_text', models.TextField(blank=True, verbose_name='OCR 추출 텍스트')),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='AI 분석 결과 JSON 데이터', verbose_name='AI 분석 결과')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student', verbose_name='학생')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='업로드한 사용자')),
            ],
            options={
                'verbose_name': '서류',
                'verbose_name_plural': '서류',
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(verbose_name='버전 번호')),
                ('file', models.FileField(upload_to='document_versions/%Y/%m/%d/', verbose_name='파일')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='파일 크기 (bytes)')),
                ('changes_description', models.TextField(blank=True, verbose_name='변경 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL, verbose_name='생성한 사용자')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='서류')),
            ],
            options={
                'verbose_name': '서류 버전',
                'verbose_name_plural': '서류 버전',
                'db_table': 'document_versions',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
