# Generated by Django 4.2.9 on 2025-12-31 06:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "analysis_version",
                    models.IntegerField(
                        default=1,
                        help_text="같은 문서를 여러 번 분석할 수 있음",
                        verbose_name="분석 버전",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기중"),
                            ("PROCESSING", "처리중"),
                            ("COMPLETED", "완료"),
                            ("FAILED", "실패"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="분석 상태",
                    ),
                ),
                (
                    "ocr_result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        {\n            "자율활동": "...",\n            "동아리활동": "...",\n            "봉사활동": "...",\n            "진로활동": "...",\n            "교과세특": {\n                "국어": "...",\n                "수학": "..."\n            }\n        }\n        ',
                        verbose_name="OCR 결과",
                    ),
                ),
                (
                    "analysis_result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        {\n            "학업역량": {"점수": 85, "분석": "..."},\n            "전공적합성": {"점수": 90, "분석": "..."},\n            "발전가능성": {"점수": 80, "분석": "..."},\n            "인성": {"점수": 88, "분석": "..."}\n        }\n        ',
                        verbose_name="AI 분석 결과",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="분석 시작 시각"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="분석 완료 시각"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "문서 분석",
                "verbose_name_plural": "문서 분석",
                "db_table": "document_analysis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="documentversion",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="document",
        ),
        migrations.RemoveField(
            model_name="document",
            name="ai_analysis",
        ),
        migrations.RemoveField(
            model_name="document",
            name="ocr_text",
        ),
        migrations.AddField(
            model_name="document",
            name="is_latest",
            field=models.BooleanField(default=True, verbose_name="최신 버전 여부"),
        ),
        migrations.AddField(
            model_name="document",
            name="version",
            field=models.IntegerField(default=1, verbose_name="버전"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["student", "is_latest"], name="documents_student_8b269a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["student", "version"], name="documents_student_0e90a9_idx"
            ),
        ),
        migrations.DeleteModel(
            name="DocumentVersion",
        ),
        migrations.AddField(
            model_name="documentanalysis",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="documents.document",
                verbose_name="문서",
            ),
        ),
        migrations.AddField(
            model_name="documentanalysis",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_analyses",
                to="students.student",
                verbose_name="학생",
            ),
        ),
        migrations.AddIndex(
            model_name="documentanalysis",
            index=models.Index(
                fields=["document"], name="document_an_documen_d6b916_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentanalysis",
            index=models.Index(
                fields=["student"], name="document_an_student_4db2f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentanalysis",
            index=models.Index(fields=["status"], name="document_an_status_db3868_idx"),
        ),
    ]
