# Generated by Django 4.2.9 on 2025-12-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_documentanalysis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[("생기부", "생활기록부"), ("모의고사", "모의고사 성적표")],
                default="생기부",
                max_length=20,
                verbose_name="문서 타입",
            ),
        ),
    ]
