# Generated by Django 4.2.9 on 2026-01-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_document_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/%Y/%m/%d/",
                verbose_name="파일",
            ),
        ),
        migrations.AlterField(
            model_name="documentanalysis",
            name="analysis_result",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        생기부 분석 결과 (AI 모듈 output):\n        {\n            "강점요약": {"첫번째_강점": "", "두번째_강점": "", "세번째_강점": ""},\n            "약점요약": {"첫번째_약점": "", "두번째_약점": "", "세번째_약점": ""},\n            "생기부_진단개요": {"한줄 요약": "", "본문": ""},\n            "진로적합성_강화방안": {\n                "강화방안": {...},\n                "비교과_지도필요_영역": {...},\n                "전공_관련_탐구_및_독서활동": {...}\n            }\n        }\n        ',
                verbose_name="AI 분석 결과",
            ),
        ),
    ]
