# Generated by Django 5.0.1 on 2025-12-30 04:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('specialization', models.CharField(blank=True, help_text='예: 이공계, 인문계, 의대 등', max_length=100, verbose_name='전문 분야')),
                ('max_students', models.IntegerField(default=30, verbose_name='최대 담당 학생 수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '컨설턴트',
                'verbose_name_plural': '컨설턴트',
                'db_table': 'consultants',
            },
        ),
    ]
