# Generated by Django 5.0.1 on 2025-12-30 04:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('student_code', models.CharField(max_length=50, unique=True, verbose_name='학생 코드')),
                ('grade', models.CharField(choices=[('1', '고1'), ('2', '고2'), ('3', '고3'), ('GRADUATED', '졸업생')], max_length=20, verbose_name='학년')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='학부모 연락처')),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('INACTIVE', '비활성'), ('GRADUATED', '졸업')], default='ACTIVE', max_length=20, verbose_name='상태')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='consultants.consultant', verbose_name='담당 컨설턴트')),
                ('high_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.highschool', verbose_name='고등학교')),
            ],
            options={
                'verbose_name': '학생',
                'verbose_name_plural': '학생',
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDesiredUniversity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100, verbose_name='학과')),
                ('priority', models.CharField(choices=[('FIRST', '1지망'), ('SECOND', '2지망'), ('THIRD', '3지망'), ('SAFETY', '안전')], max_length=20, verbose_name='우선순위')),
                ('admission_type', models.CharField(blank=True, help_text='예: 학생부종합, 학생부교과, 논술 등', max_length=50, verbose_name='전형 유형')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desired_universities', to='students.student', verbose_name='학생')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desired_by_students', to='schools.university', verbose_name='대학')),
            ],
            options={
                'verbose_name': '학생 지망 대학',
                'verbose_name_plural': '학생 지망 대학',
                'db_table': 'student_desired_universities',
                'ordering': ['priority'],
                'unique_together': {('student', 'university', 'department')},
            },
        ),
    ]
