# Generated by Django 5.0.1 on 2025-12-30 04:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('INITIAL', '초기 상담'), ('PROGRESS', '진행 상황'), ('MONTHLY', '월간 리포트'), ('FINAL', '최종 리포트'), ('SPECIAL', '특별 리포트')], max_length=20, verbose_name='리포트 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('summary', models.TextField(blank=True, verbose_name='요약')),
                ('content', models.TextField(verbose_name='내용')),
                ('current_status', models.JSONField(blank=True, default=dict, help_text='성적, 활동 등 현재 상황', verbose_name='현재 상황')),
                ('university_analysis', models.JSONField(blank=True, default=dict, help_text='지망 대학 합격 가능성 분석', verbose_name='목표 대학 분석')),
                ('improvement_plan', models.TextField(blank=True, verbose_name='개선 계획')),
                ('action_items', models.JSONField(blank=True, default=list, help_text='구체적인 실행 항목 리스트', verbose_name='실행 항목')),
                ('ai_insights', models.JSONField(blank=True, default=dict, help_text='AI 분석을 통한 추가 인사이트', verbose_name='AI 인사이트')),
                ('status', models.CharField(choices=[('DRAFT', '작성중'), ('COMPLETED', '완료'), ('SENT', '전송됨')], default='DRAFT', max_length=20, verbose_name='상태')),
                ('report_file', models.FileField(blank=True, help_text='PDF 등 생성된 리포트 파일', null=True, upload_to='reports/%Y/%m/%d/', verbose_name='리포트 파일')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='전송 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_reports', to='consultants.consultant', verbose_name='컨설턴트')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_reports', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '컨설팅 리포트',
                'verbose_name_plural': '컨설팅 리포트',
                'db_table': 'consultation_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('ONLINE', '온라인'), ('OFFLINE', '오프라인'), ('PHONE', '전화')], max_length=20, verbose_name='상담 유형')),
                ('session_date', models.DateTimeField(verbose_name='상담 일시')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='소요 시간 (분)')),
                ('topics_discussed', models.JSONField(blank=True, default=list, help_text='상담에서 논의된 주제 리스트', verbose_name='논의 주제')),
                ('notes', models.TextField(verbose_name='상담 내용')),
                ('next_actions', models.TextField(blank=True, verbose_name='다음 액션')),
                ('next_session_date', models.DateTimeField(blank=True, null=True, verbose_name='다음 상담 예정일')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='상담 관련 첨부 파일 정보', verbose_name='첨부 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_sessions', to='consultants.consultant', verbose_name='컨설턴트')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_sessions', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '상담 세션',
                'verbose_name_plural': '상담 세션',
                'db_table': 'consultation_sessions',
                'ordering': ['-session_date'],
            },
        ),
    ]
